// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Amenity struct {
	AmenityCode string         `json:"amenity_code"`
	Description sql.NullString `json:"description"`
}

type Destination struct {
	DestinationID uuid.UUID      `json:"destination_id"`
	Address       sql.NullString `json:"address"`
	Country       sql.NullString `json:"country"`
	Type          sql.NullString `json:"type"`
	Location      interface{}    `json:"location"`
	Boundary      interface{}    `json:"boundary"`
}

type Hotel struct {
	HotelID       uuid.UUID       `json:"hotel_id"`
	DestinationID uuid.NullUUID   `json:"destination_id"`
	TypeID        sql.NullString  `json:"type_id"`
	TotalRoom     sql.NullInt32   `json:"total_room"`
	Rating        sql.NullFloat64 `json:"rating"`
}

type Medium struct {
	MediaID     uuid.UUID      `json:"media_id"`
	RoomID      uuid.NullUUID  `json:"room_id"`
	Url         sql.NullString `json:"url"`
	Type        sql.NullString `json:"type"`
	Description sql.NullString `json:"description"`
	IsPrimary   sql.NullBool   `json:"is_primary"`
}

type Rate struct {
	RoomID  uuid.UUID       `json:"room_id"`
	UserID  string          `json:"user_id"`
	Score   sql.NullFloat64 `json:"score"`
	Comment sql.NullString  `json:"comment"`
}

type Reservation struct {
	ReservationID uuid.UUID      `json:"reservation_id"`
	RoomID        uuid.NullUUID  `json:"room_id"`
	UserID        sql.NullString `json:"user_id"`
	StartDate     sql.NullTime   `json:"start_date"`
	EndDate       sql.NullTime   `json:"end_date"`
	Status        sql.NullString `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
	UpdateAt      sql.NullTime   `json:"update_at"`
	UpdateBy      uuid.NullUUID  `json:"update_by"`
}

type Role struct {
	RoleCode   string         `json:"role_code"`
	Desciption sql.NullString `json:"desciption"`
}

type Room struct {
	RoomID      uuid.UUID       `json:"room_id"`
	RoomName    sql.NullString  `json:"room_name"`
	HotelID     uuid.NullUUID   `json:"hotel_id"`
	Floor       sql.NullInt32   `json:"floor"`
	TypeID      sql.NullString  `json:"type_id"`
	MaxCapacity sql.NullInt32   `json:"max_capacity"`
	Rate        sql.NullFloat64 `json:"rate"`
	Description sql.NullString  `json:"description"`
	Price       sql.NullInt32   `json:"price"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	CreatedBy   uuid.NullUUID   `json:"created_by"`
	UpdateAt    sql.NullTime    `json:"update_at"`
	UpdateBy    uuid.NullUUID   `json:"update_by"`
}

type RoomAmenity struct {
	RoomID      uuid.UUID `json:"room_id"`
	AmenityCode string    `json:"amenity_code"`
}

type Type struct {
	TypeCode    string         `json:"type_code"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	UpdateAt    sql.NullTime   `json:"update_at"`
	UpdateBy    uuid.NullUUID  `json:"update_by"`
}

type User struct {
	Username string         `json:"username"`
	Role     sql.NullString `json:"role"`
}
