// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateHotel(ctx context.Context, arg CreateHotelParams) (Hotel, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	DeleteHotel(ctx context.Context, hotelID uuid.UUID) error
	DeleteReservation(ctx context.Context, reservationID uuid.UUID) error
	DeleteRoom(ctx context.Context, roomID uuid.UUID) error
	GetAvailableRooms(ctx context.Context, arg GetAvailableRoomsParams) ([]Room, error)
	GetHotel(ctx context.Context, hotelID uuid.UUID) (Hotel, error)
	GetReservation(ctx context.Context, reservationID uuid.UUID) (Reservation, error)
	GetReservationsByDateRange(ctx context.Context, arg GetReservationsByDateRangeParams) ([]Reservation, error)
	GetRoom(ctx context.Context, roomID uuid.UUID) (Room, error)
	ListHotels(ctx context.Context, arg ListHotelsParams) ([]Hotel, error)
	ListHotelsByDestination(ctx context.Context, arg ListHotelsByDestinationParams) ([]Hotel, error)
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error)
	ListReservationsByRoom(ctx context.Context, arg ListReservationsByRoomParams) ([]Reservation, error)
	ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]Reservation, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error)
	ListRoomsByHotel(ctx context.Context, arg ListRoomsByHotelParams) ([]Room, error)
	UpdateHotel(ctx context.Context, arg UpdateHotelParams) (Hotel, error)
	UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error)
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
